#
# INTERNAL SYSTEM STUFF
#

index:
    path:     /
    defaults: { _controller: AppBundle:Static:index }

login:
    path:     /login
    defaults: { _controller: AppBundle:Auth:login }

login_check:
    path:     /login/check

logout:
    path:     /logout


#
# FRONT PAGE
#

#home:
#    path:     /home
#    defaults: { _controller: AppBundle:Index:index }
#
#promo:
#    path:     /promo
#    defaults: { _controller: AppBundle:Index:promo }


#
# NEWS
#

#news:
#    path:     /news
#    defaults: { _controller: AppBundle:News:index }
#
#newsAdd:
#    path:     /news/add
#    defaults: { _controller: AppBundle:News:add }
#    methods:  [POST]
#
#newsDelete:
#    path:     /news/delete/{id}
#    defaults: { _controller: AppBundle:News:delete }
#    methods:  [POST]
#    requirements:
#        id: '\d+'

#
# VIDEO GAMES
#
#videoGames:
#    path:     /vidya-in-2017
#    defaults: { _controller: AppBundle:VideoGames:index }
#    methods:  [GET]
#
#addVideoGame:
#    path:     /vidya-in-2017
#    defaults: { _controller: AppBundle:VideoGames:add }
#    methods:  [POST]

#
# CREW
#

people:
    path:     /crew
    defaults: { _controller: AppBundle:People:index }

permissions:
    path:     /crew/permissions
    defaults: { _controller: AppBundle:People:permissions }

addPerson:
    path:     /crew/new
    defaults: { _controller: AppBundle:People:new }

userSearch:
    path:     /crew/search
    methods:  [POST]
    defaults: { _controller: AppBundle:People:search }

viewPerson:
    path:     /crew/{steamID}
    defaults: { _controller: AppBundle:People:view }
    requirements:
        steamID: '\d+'

editPerson:
    path:     /crew/{steamID}/edit
    methods:  [GET]
    defaults: { _controller: AppBundle:People:edit }
    requirements:
        steamID: '\d+'

editPersonPost:
    path:     /crew/{steamID}/edit
    methods:  [POST]
    defaults: { _controller: AppBundle:People:post }
    requirements:
        steamID: '\d+'

#
# AWARDS
#

#awards:
#    path:     /awards
#    methods:  [GET]
#    defaults: { _controller: AppBundle:Award:index }
#
#awardFrontendPost:
#    path:     /awards
#    methods:  [POST]
#    defaults: { _controller: AppBundle:Award:post }
#
#awardManager:
#    path:     /awards/manage
#    methods:  [GET]
#    defaults: { _controller: AppBundle:AwardAdmin:managerList }
#
#awardManagerPost:
#    path:     /awards/manage
#    methods:  [POST]
#    defaults: { _controller: AppBundle:AwardAdmin:managerPost }
#
#awardManagerPostAjax:
#    path:     /awards/manage/ajax
#    methods:  [POST]
#    defaults: { _controller: AppBundle:AwardAdmin:managerPostAjax }
#
#nomineeManager:
#    path:     /nominees/{awardID}
#    methods:  [GET]
#    defaults: { _controller: AppBundle:Nominee:index, awardID: null }
#
#nomineePost:
#    path:     /nominees/{awardID}
#    methods:  [POST]
#    defaults: { _controller: AppBundle:Nominee:post }

#
# TASKS
#

#tasks:
#    path:     /tasks
#    methods:  [GET]
#    defaults: { _controller: AppBundle:Tasks:index }
#
#tasksImageCheck:
#    path:     /tasks/check-images
#    defaults: { _controller: AppBundle:Tasks:imageCheck }
#
#tasksPost:
#    path:     /tasks
#    methods:  [POST]
#    defaults: { _controller: AppBundle:Tasks:post }

#
# VOTING
#

#viewVotingCode:
#    path:     /vote/code
#    defaults: { _controller: AppBundle:Voting:codeViewer }
#
#voting:
#    path:     /vote/{awardID}
#    methods:  [GET]
#    defaults: { _controller: AppBundle:Voting:index, awardID: null }
#
#votingSubmission:
#    path:     /vote/{awardID}
#    methods:  [POST]
#    defaults: { _controller: AppBundle:Voting:post }
#
#voteWithCode:
#    path:     /vote/v/{code}
#    defaults: { _controller: AppBundle:Voting:codeEntry }
#    requirements:
#        code: '.+'

#
# RESULTS
#

#winners:
#    path:     /winners
#    methods:  [GET]
#    defaults: { _controller: AppBundle:Result:simple }
#
#winnerImageUpload:
#    path:     /winners
#    methods:  [POST]
#    defaults: { _controller: AppBundle:Result:winnerImageUpload }
#
#results:
#    path:     /results/{all}
#    defaults: { _controller: AppBundle:Result:detailed, 'all': null }
#    requirements:
#        all: '(all)?'
#
#pairwiseResults:
#    path:     /results/pairwise
#    defaults: { _controller: AppBundle:Result:pairwise }

#
# REFERRERS
#

referrers:
    path:     /referrers
    defaults: { _controller: AppBundle:Referrer:index }

#
# AUDIT LOG
#

auditLog:
    path:     /audit-log
    defaults: { _controller: AppBundle:AuditLog:index }

#
# LAUNCHER
#

countdown:
    path:     /countdown
    defaults: { _controller: AppBundle:Launcher:countdown }

stream:
    path:     /stream
    defaults: { _controller: AppBundle:Launcher:stream }

finished:
    path:     /finished
    defaults: { _controller: FrameworkBundle:Template:template, template: 'finished.html.twig' }

#
# STATIC PAGES
#

privacy:
    path:     /privacy
    defaults: { _controller: FrameworkBundle:Template:template, template: 'privacy.html.twig' }

#videos:
#    path:     /videos
#    defaults: { _controller: FrameworkBundle:Template:template, template: 'videos.html.twig' }
#
#soundtrack:
#    path:     /soundtrack
#    defaults: { _controller: FrameworkBundle:Template:template, template: 'soundtrack.html.twig' }
#
#credits:
#    path:     /credits
#    defaults: { _controller: FrameworkBundle:Template:template, template: 'credits.html.twig' }
#
#resultRedirect:
#    path:     /voting/results
#    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: 'results' }

#
# CONFIG
#

config:
    path:     /config
    methods:  [GET]
    defaults: { _controller: AppBundle:Config:index }

configPost:
    path:     /config
    methods:  [POST]
    defaults: { _controller: AppBundle:Config:post }

#
# SPECIAL
#

#itemManager:
#    path:     /lootboxes
#    methods:  [GET]
#    defaults: { _controller: AppBundle:ItemManager:index }
#
#itemPost:
#    path:     /lootboxes
#    methods:  [POST]
#    defaults: { _controller: AppBundle:ItemManager:post }
#
#advertManager:
#    path:     /adverts
#    defaults: { _controller: AppBundle:AdvertManager:index }
#    methods:  [GET]
#
#advertPost:
#    path:     /adverts
#    methods:  [POST]
#    defaults: { _controller: AppBundle:AdvertManager:post }
#
#advertRedirect:
#    path:     /link/{advertToken}
#    defaults: { _controller: AppBundle:AdvertManager:redirect }
#    requirements:
#        advertToken: '^[0-9a-f]+$'

#
# /V/3
#

obsOverlay:
    path:     /obs/overlay
    defaults: { _controller: AppBundle:Obs:overlay }

sentimentAjax:
    path:     /obs/sentiment
    methods:  [POST]
    defaults: { _controller: AppBundle:Obs:getSentiment }
